# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import temperature_pb2 as temperature__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in temperature_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperatureConverterStub(object):
    """Сервис с двумя RPC-методами
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ToCelsius = channel.unary_unary(
                '/temperature.TemperatureConverter/ToCelsius',
                request_serializer=temperature__pb2.FahrenheitRequest.SerializeToString,
                response_deserializer=temperature__pb2.CelsiusResponse.FromString,
                _registered_method=True)
        self.ToFahrenheit = channel.unary_unary(
                '/temperature.TemperatureConverter/ToFahrenheit',
                request_serializer=temperature__pb2.CelsiusRequest.SerializeToString,
                response_deserializer=temperature__pb2.FahrenheitResponse.FromString,
                _registered_method=True)


class TemperatureConverterServicer(object):
    """Сервис с двумя RPC-методами
    """

    def ToCelsius(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToFahrenheit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ToCelsius': grpc.unary_unary_rpc_method_handler(
                    servicer.ToCelsius,
                    request_deserializer=temperature__pb2.FahrenheitRequest.FromString,
                    response_serializer=temperature__pb2.CelsiusResponse.SerializeToString,
            ),
            'ToFahrenheit': grpc.unary_unary_rpc_method_handler(
                    servicer.ToFahrenheit,
                    request_deserializer=temperature__pb2.CelsiusRequest.FromString,
                    response_serializer=temperature__pb2.FahrenheitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperature.TemperatureConverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temperature.TemperatureConverter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TemperatureConverter(object):
    """Сервис с двумя RPC-методами
    """

    @staticmethod
    def ToCelsius(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature.TemperatureConverter/ToCelsius',
            temperature__pb2.FahrenheitRequest.SerializeToString,
            temperature__pb2.CelsiusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToFahrenheit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature.TemperatureConverter/ToFahrenheit',
            temperature__pb2.CelsiusRequest.SerializeToString,
            temperature__pb2.FahrenheitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
