# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\x0btemperature\"\'\n\x11\x46\x61hrenheitRequest\x12\x12\n\nfahrenheit\x18\x01 \x01(\x01\"!\n\x0e\x43\x65lsiusRequest\x12\x0f\n\x07\x63\x65lsius\x18\x01 \x01(\x01\"\"\n\x0f\x43\x65lsiusResponse\x12\x0f\n\x07\x63\x65lsius\x18\x01 \x01(\x01\"(\n\x12\x46\x61hrenheitResponse\x12\x12\n\nfahrenheit\x18\x01 \x01(\x01\x32\xaf\x01\n\x14TemperatureConverter\x12I\n\tToCelsius\x12\x1e.temperature.FahrenheitRequest\x1a\x1c.temperature.CelsiusResponse\x12L\n\x0cToFahrenheit\x12\x1b.temperature.CelsiusRequest\x1a\x1f.temperature.FahrenheitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAHRENHEITREQUEST']._serialized_start=34
  _globals['_FAHRENHEITREQUEST']._serialized_end=73
  _globals['_CELSIUSREQUEST']._serialized_start=75
  _globals['_CELSIUSREQUEST']._serialized_end=108
  _globals['_CELSIUSRESPONSE']._serialized_start=110
  _globals['_CELSIUSRESPONSE']._serialized_end=144
  _globals['_FAHRENHEITRESPONSE']._serialized_start=146
  _globals['_FAHRENHEITRESPONSE']._serialized_end=186
  _globals['_TEMPERATURECONVERTER']._serialized_start=189
  _globals['_TEMPERATURECONVERTER']._serialized_end=364
# @@protoc_insertion_point(module_scope)
